### ISSUE TITLE
icons not working

### ISSUE THREAD

**Issue by ricbermo** [b-ryan/powerline-shell#218]
Hi there. I just follow the instructions and it's not working. I'm on archlinux + zsh.
This is how it looks
![captura de pantalla de 2015-12-18 21-20-30](https://cloud.githubusercontent.com/assets/2601363/11910780/68b2c10a-a5cd-11e5-9738-7831ddf6f4a8.png)

**Comment by b-ryan** [comment]
Hi @ricbermo can you confirm you followed the instructions on patching your fonts? It's in the Setup portion of the readme: https://github.com/milkbikis/powerline-shell#setup

**Comment by ricbermo** [comment]
yes. checked out the fonts repo, cd into the folder and ./install.sh, right?

**Comment by zackcote** [comment]
Same problem in ubuntu. Set my terminal to one of the installed powerline fonts -- still no icons.

**Comment by erolg** [comment]
![screenshot from 2016-03-08 13 49 09](https://cloud.githubusercontent.com/assets/5674144/13600897/add0c664-e534-11e5-9df3-9e6ac483ffdc.png)

Same problem

**Comment by mbacvanski** [comment]
Same problem in Mac OSX, all icons appear as unrecognized symbols.

**Comment by badmonster-nc** [comment]
same problem on xubuntu 15.10

**Comment by mbacvanski** [comment]
Solved it by using fonts from [here](https://github.com/powerline/fonts)

**Comment by ricbermo** [comment]
@mbacvanski worked on linux or osx? tried on linux w/o success.

**Comment by mbacvanski** [comment]
@ricbermo Worked on mac - set Terminal's font to one of the `* for Powerline` fonts

**Comment by gontovnik** [comment]
Any ideas how to fix that on Mac OS? I have still the same issue. Tried to set font of terminal to any of Powerline fonts, still the same.

**Comment by nobodyme** [comment]
Facing same problem on mint, any solutions yet?
