### ISSUE TITLE
segments/jobs.py does not work in fish shell

### ISSUE THREAD

**Issue by robertoloja** [b-ryan/powerline-shell#228]
`num_jobs == -1` regardless of the number of background jobs.

However, when I simply change line 8 to
`pppid = os.getppid()`
then num_jobs reports the number of background processes correctly. 

Similarly, if line 8 is left alone but line 6 is changed to use 
`os.getpid()` 
rather than 
`os.getppid()`
then num_jobs also reports the correct number of bakground processes. 

I will check if this is also the case in other shells.

**Comment by robertoloja** [comment]
Making the change I outlined above breaks the jobs.py functionality on bash. Maybe this needs to check os.getenv("SHELL")

**Comment by jceaser** [comment]
I'm not sure what the intention is, but would you like to have "ps -T" instead? I don't use this segment, but I use fish and I have a development setup ready to go.
