### ISSUE TITLE
Install powerline-shell in Microsoft Windows

### ISSUE THREAD

**Issue by IamGianluca** [b-ryan/powerline-shell#229]
Hi, 

I've been a long time user of powerline-shell in both Linux and Mac. On my new job I have a Windows machine and I wanted to install powerline-shell. Is that even possible? On Windows there is no .bashrc file, so I don't know how to proceed.

Many thanks,

Gianluca

**Comment by MartinSGill** [comment]
I'm trying to get it working in powershell right now.
Installation seems to have gone without a hitch. The "jobs" segment needs to be disabled as the concept (as implemented) isn't known on windows.

I'm currently trying to figure out the error:

`UnicodeEncodeError: 'charmap' codec can't encode character '\ue0b1' in position 68: character maps to <undefined>`

Once I've got the errors fixed it's just a case of adding it to my powershell profile

`~\Documents\WindowsPowerShell\profile.ps1`

```
function prompt {
  python ~/powerline-shell.py
  return ""
}
```

**Comment by erm0l0v** [comment]
Hi I added pull request to fix this issue

**Comment by erm0l0v** [comment]
I use python 3.6.2 and Windows 10

The problem is in Windows default locale - `'en_US.cp1252'`
Method `locale.getpreferredencoding` returns `'cp1252'` that's why python use encoding `cp1252` by default instead `utf-8`

To reproduce this error you can use this command
```
$ PYTHONIOENCODING=cp1252 ./powerline-shell.py
```

### Quick fix

set environment variable `PYTHONIOENCODING` to `utf-8` :
```
export PYTHONIOENCODING=UTF-8
```

**Comment by b-ryan** [comment]
Hey @erm0l0v thanks for the info. I am able to reproduce it as you instructed, but only with a very old version of powerline-shell. Nowadays the code is installed via `pip` - I wonder if installation this way fixes this sort of issue? Or perhaps something else changed.

I would be curious whether anyone still has this issue with the latest version of this project.

**Comment by gspalato** [comment]
I still have this error with the latest version installed by pip. @erm0l0v's fiz didn't work for me. I wonder if there's any solution?

**Comment by vicenteherrera** [comment]
You must also install and set your terminal to use a font patched for powerline
https://github.com/powerline/fonts

Also if you get this error:
`ps: unknown option --o`

Create a config file, as explained here
https://github.com/b-ryan/powerline-shell#config-file
Then, edit .config/powerline-shell/config.json and remove the line:
`  "jobs",`
