### ISSUE TITLE
rxvt-unicode-256color powerline-shell issue no ">" was displayed

### ISSUE THREAD

**Issue by bluezd** [b-ryan/powerline-shell#233]
```
rxvt-unicode-9.21-3.fc21.x86_64
rxvt-unicode-256color-9.21-3.fc21.x86_64
```

Detail please check this pic as below:
https://imagebin.ca/v/2ctVBFcLxuy1

Could anybody tell me what is going wrong ? Thanks !

**Comment by bluezd** [comment]
Anyone knows ?

**Comment by SethBarberee** [comment]
What font are you using? Some fonts aren't patched for powerline and that would be the case with yours.

**Comment by bluezd** [comment]
urxvt256c*font: xft:Bitstream\ Vera\ Sans\ Mono:style=roman:pixelsize=16, xft:youyuan:style=roman:pixelsize=16

Here is the font.

**Comment by SethBarberee** [comment]
Wouldn't those two be in conflict? I run Arch with the 256xresources enabled but I had to remove the regular rxvt-unicode for colors to work so probably fonts would be the same.

**Comment by bluezd** [comment]
urxvt doesn't work either, but it works in gnome-terminal. I changed my fonts issue persist all the time Really has no idea about it,

**Comment by SethBarberee** [comment]
Like icons popup in gnome-terminal? I use this in my xresources: xft:
Cousine for Powerline:size=13

On Sun, Apr 10, 2016 at 10:19 PM, Dong <notifications@github.com> wrote:

> urxvt doesn't work either, but it works in gnome-terminal. I changed my
> fonts issue persist all the time Really has no idea about it,
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/milkbikis/powerline-shell/issues/233#issuecomment-208144855>
>



-- 
Yours in Brotherhood,
Seth Barberee
Penateka Lodge Vice Chief of Service

**Comment by bluezd** [comment]
I tried this font again but still not work.

Below is the gnome-terminal screen shot.
https://imagebin.ca/v/2dLcJWkQiuom

**Comment by SethBarberee** [comment]
Hmm I believe you aren't setting the xresources for Urxvt correctly. It should just be:
Urxvt*font: xft: FontNameHere

256c isn't required in the xresources because the name is urxvt not urxvt256c

**Comment by bluezd** [comment]
Tried again, still not work.

Below is my urxvt configuration file:
http://pastebin.ubuntu.com/15753042/

**Comment by SethBarberee** [comment]
The font of mine is a powerline patched font.. Did you download it? That could be one reason it doesn't work.. My xresources: https://github.com/SethBarberee/dotfiles/blob/master/Xresources

**Comment by bluezd** [comment]
Where can I get the parched font ? I can have a try again.

**Comment by SethBarberee** [comment]
Here ya go!
https://github.com/powerline/fonts

On Mon, Apr 11, 2016 at 8:25 PM, Dong <notifications@github.com> wrote:

> Where can I get the parched font ? I can have a try again.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/milkbikis/powerline-shell/issues/233#issuecomment-208654784>
>



-- 
Yours in Brotherhood,
Seth Barberee
Penateka Lodge Vice Chief of Service

**Comment by SethBarberee** [comment]
Is it still the box issue? Make sure that you actually ran the script to install the font and remember to update your font-cache.

**Comment by bluezd** [comment]
I ran the run.sh for installing the fonts and I make sure the fonts has been installed successfully.

**Comment by bluezd** [comment]
Any other thoughts here ?

**Comment by SethBarberee** [comment]
I still think that those two packages are conflicting... The base rxvt-Unicode package and the xresources package might be in conflict..

**Comment by bluezd** [comment]
Any other solutions here ?

**Comment by luzfcb** [comment]
I install all fonts from https://github.com/powerline/fonts and open the "profile preferencies" on gnome-terminal and change the font to "Ubuntu Mono derivative Powerline Regular"

**Comment by bluezd** [comment]
I use rxvt as my default terminal not gnome-terminal.

**Comment by dmaglio** [comment]
same issue for my, in rxvt-unicode-256 don't works, but in terminator yes. same font "Inconsolata for Powerline"

**Comment by mvf** [comment]
Works fine over here.
```
rxvt-unicode (urxvt) v9.22 - released: 2016-01-23
options: perl,xft,styles,combining,blink,iso14755,unicode3,encodings=eu+vn+jp+jp-ext+kr+zh+zh-ext,fade,transparent,tint,XIM,frills,selectionscrolling,wheel,slipwheel,smart-resize,cursorBlink,pointerBlank,scrollbars=plain+rxvt+NeXT+xterm
```
`.Xresources` snippet:
```
URxvt*font: xft:Consolas:style=Regular:pixelsize=15,xft:Inconsolata for Powerline:pixelsize=15
URxvt*boldFont:
URxvt*italicFont:
URxvt*boldItalicFont:
```
The empty definitions disable bold and italic fonts by mapping them to the `URxvt*font` font list. Escaping spaces in font names is not necessary. Make sure to run `xrdb -m .Xresources` to apply the settings.

**Comment by b-ryan** [comment]
Any word on whether this is still an issue for anyone?
