### ISSUE TITLE
Zsh prompt not working inside VM

### ISSUE THREAD

**Issue by HongchangWu** [b-ryan/powerline-shell#285]
Have a Vagrant VM inside mac. Everything works fine on the host. However inside the VM the zsh prompt looks like this:

![screen shot 2017-09-14 at 2 58 37 pm](https://user-images.githubusercontent.com/362833/30450038-ab24ceb2-995e-11e7-8aad-1f8fa4a67700.png)

Strangely in the same VM if I `chsh` and use the bash setup everything works fine. 

Host environment:
- macOS Sierra 10.12.6
- iTerm2 3.0.15 with patched font from [Powerline Fonts](https://github.com/powerline/fonts)
- Vagrant 1.9.8

VM environment:
- Linux version 3.10.0-514.6.1.el7.x86_64 (builder@kbuilder.dev.centos.org)
- zsh 5.4.1 
- Python 2.7.13
- pip 9.0.1
- `echo $LANG` -> `en_US.UTF-8`

**Comment by b-ryan** [comment]
Did you install powerline-shell via pip?

Can you post the portion of your .zshrc that sets powerline?

**Comment by HongchangWu** [comment]
Yeah. installed via `pip install --user powerline-shell`.

`.zshrc` portion that sets `powerline-shell`:

```zsh
unset RPS1

# Powerline shell
function powerline_precmd() {
    PS1="$(powerline-shell $? --shell zsh 2> /dev/null)"
}

function install_powerline_precmd() {
  for s in "${precmd_functions[@]}"; do
    if [ "$s" = "powerline_precmd" ]; then
      return
    fi
  done
  precmd_functions+=(powerline_precmd)
}

if [ "$TERM" != "linux" ]; then
    install_powerline_precmd
fi
```

**Comment by b-ryan** [comment]
Is there any chance you have a minimal vagrantfile you could give me so I could try it out myself?

**Comment by b-ryan** [comment]
Following up on my previous comment. It's hard for me to do anything here since it could be very system specific.
