### ISSUE TITLE
Extra space in each segment in Bash on Ubuntu on Windows

### ISSUE THREAD

**Issue by shikhanshu** [b-ryan/powerline-shell#305]
I am using powerline-shell in Bash on Ubuntu on Windows (WSL on Windows 10). I have installed patched fonts and am able to use powerline-shell without issues.

Except:
![image](https://user-images.githubusercontent.com/31578/31589901-a2d435e6-b1bd-11e7-987a-c4dc8a972c61.png)

Every segment has a space in it's beginning. I have tried different patched fonts, all with same behavior. My config is simple:
![image](https://user-images.githubusercontent.com/31578/31589913-be89c6e8-b1bd-11e7-88d8-56e1104ff220.png)

**Comment by b-ryan** [comment]
Can you show the actual output of the `powerline-shell` command?

**Comment by shikhanshu** [comment]
I don't see the issue anymore. Updated+upgraded my WSS and updated to latest powerline-shell and all's great now!

**Comment by b-ryan** [comment]
woot woot!
