### ISSUE TITLE
"git" feature busted in python 2.6 

### ISSUE THREAD

**Issue by rlauer6** [b-ryan/powerline-shell#310]
s = u" {}{} " .format(self.n_or_empty(_key), self.symbols[_key])
ValueError: zero length field name in format

* this seemed to fix

  s = u" {0}{1} " .format(self.n_or_empty(_key), self.symbols[_key])

**Comment by b-ryan** [comment]
I am going to take the route of not supporting python 2.6. If someone is able to provide a compelling reason for it to be supported I am open to changing my mind.

**Comment by blieque** [comment]
Speaking of versions, is `powerline-shell` supposed to work in both 2.7 and 3.x? I'm getting a syntax error on `except Exception, e:` in Python 3.6.5, and figured it might be version related.
