### ISSUE TITLE
Root indicator broken

### ISSUE THREAD

**Issue by b-ryan** [b-ryan/powerline-shell#315]
This broke with the code to fix bash sub-command escaping in #282

**Comment by TiGR** [comment]
Yep, root indication is broken (it is always not root, that is a dollar sign).

**Comment by peterpakos** [comment]
Yeah, does't work for me either:
<img width="262" alt="screen shot 2018-01-24 at 00 26 05" src="https://user-images.githubusercontent.com/8777471/35307956-38b14800-009d-11e8-87b2-ded81d067b03.png">

**Comment by TiGR** [comment]
Attempted to fix it, see PR #362.
