### ISSUE TITLE
Custom themes

### ISSUE THREAD

**Issue by lyze237** [b-ryan/powerline-shell#318]
Hello!

Can we add custom themes to the program?
Preferably by pointing a theme file to the config.

If we need to add it manually to the installation folder, where is it installed to?

**Comment by jceaser** [comment]
you want to have a theme externally defined that you just config your way in?

**Comment by jceaser** [comment]
I have some code that I think will work for you:

https://github.com/jceaser/powerline-shell/commit/c399061f82283da5b4a6cc41fd703943d2e8a7c7#diff-0907db71f0799acf6b7b78da10c96b1a

This code will allow you to add settings such as:

"theme-overrides":{"PATH_BG":31, "PATH_FG":15}

and it will iterate over them overriding the matching value in the Theme Color object. Looking for comments, I'll issue a pull request in a couple of days if I don't hear anything.

**Comment by b-ryan** [comment]
Yeah this was an issue I knew about recently. It's a regression I introduced in #280 and have been meaning to get to.

The plan for fixing is to allow the "theme" in the config to point to any file on disk and load the theme from there.

**Comment by jceaser** [comment]
so then you would not be interested in my change if that is the case?

**Comment by b-ryan** [comment]
Unfortunately not :) My reasoning is that themes makes sense as classes - they could be packaged up and distributed by third parties. And I do not want more than one way to write themes (ie config file vs theme classes). Need to keep things as simple as possible.

**Comment by jceaser** [comment]
got it

**Comment by b-ryan** [comment]
Fixed this issue in #352 - although I am still open to doing this a different way, including @jceaser's change. But I am just going to close this and if anyone feels strongly about how this should work, will be happy to discuss. Right now it's low priority for me to change the functionality.

**Comment by jceaser** [comment]
does this mean that you have not included my change? Can we make this a "project" here and hash it out?

**Comment by b-ryan** [comment]
We can just re-open this if you want to hash it out. My point was just that I don't exactly like the way it's implemented currently, but I also don't care enough at the moment to change it.

What are your thoughts?

**Comment by jceaser** [comment]
I guess it did take me to long to get back to this project.
