### ISSUE TITLE
Run on cygwin - No module named "pwd"

### ISSUE THREAD

**Issue by hyperhead** [b-ryan/powerline-shell#323]
Hi,

I'm trying to run powerline-shell in Cygwin, but it is failing because python doesn't have a pwd module.  I have searched pip for a pwd module, doesnt seem to exist for Windows (there is a micropython-pwd).  Has anybody else had this problem using Cygwin.

**Comment by jceaser** [comment]
so the code references "os.getenv('PWD')" which is an environmental variable, while in cygwin, what do you get if you do 'echo $PWD'?

**Comment by ericLemanissier** [comment]
I have the same issue. It is not linked to the use of PWD environment variable, but really the import of a package which does not exist for windows.
```python
Traceback (most recent call last):
  File "c:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\powerline-shell.exe\__main__.py", line 9, in <module>
  File "c:\Python27\lib\site-packages\powerline_shell\__init__.py", line 186, in main
    mod = importlib.import_module("powerline_shell.segments." + seg_name)
  File "c:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "c:\Python27\lib\site-packages\powerline_shell\segments\username.py", line 3, in <module>
    import pwd
ImportError: No module named pwd
```

the package is then only use to get user name by calling `pwd.getpwuid(os.getuid())[0]`, so a solution could be to do 
```python
try:
    import pwd
except ImportError:
   pwd = None
   import getpass


...

if pwd:
    userName = pwd.getpwuid(os.getuid())[0]
else:
    userName = getpass.getuser()
```

**Comment by nick5435** [comment]
Still having that issue today. Using Python 3.6.3 (Anaconda ver 1.6.5), bash ver 4.4.12(1)-pc-msys )provided by GitBash), and the most recent version of `powerline-shell` installed with pip version 9.0.1.
`os.getlogin` seems to do the trick on my machine!

**Comment by channabasavagola** [comment]
Now the issue is with grp. 

`import grp
ModuleNotFoundError: No module named 'grp'`

Any workarounds for this?

**Comment by nick5435** [comment]
@channabasavagola What is the full error message that you are getting?

**Comment by channabasavagola** [comment]
> @channabasavagola What is the full error message that you are getting?

Thanks @nick5435 , we installed pypiwin32 and we did not see this error thereafter. (This is when we were trying to install supervisor for windows)
