### ISSUE TITLE
Sourcing .bashrc keeps appending a new _update_ps1

### ISSUE THREAD

**Issue by bytebeast** [b-ryan/powerline-shell#331]
In the Setup Documentation it says the following for bash:
```sh
Bash

Add the following to your .bashrc (or .profile on Mac):

function _update_ps1() {
    PS1="$(powerline-shell $?)"
}

if [ "$TERM" != "linux" ]; then
    PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
fi
```

I believe I found a bug with following line:
```sh
PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
```

I was making some iterative changes to my **.bashrc** and continuously sourcing it after making the change to test my change. After a few changes, I noticed that there was a lag drawing the prompt. After some digging I found that it kept appending **_update_ps1;** to the prompt.  This is what I ended up with for my **PROMPT_COMMAND** environment variable:

```sh
PROMPT_COMMAND=_update_ps1; _update_ps1; _update_ps1; _update_ps1; _update_ps1; _update_ps1; 
```

**Comment by b-ryan** [comment]
Ah yeah - that's pretty lame. I'm surprised this has been hanging around for so long.

An easy fix would be to check if the PROMPT_COMMAND string already contains _update_ps1. Another would be to have the script set some environmental variable indicating it has been set.

**Comment by b-ryan** [comment]
Actually maybe I did notice this at some point. My bashrc just contains:

```
_update_ps1() {
    # PS1="$(powerline-shell.py --cwd-mode plain --mode flat $?)"
    PS1="$(powerline-shell $?)"
}

if [ "$TERM" != "linux" ]; then
    PROMPT_COMMAND=_update_ps1
fi
```

I didn't write the original instructions so I don't know why the instructions don't just say to do this. I think I may just update the instructions to the above.
