### ISSUE TITLE
Themes with Hex-Colors

### ISSUE THREAD

**Issue by weilbith** [b-ryan/powerline-shell#336]
I wanna create my own theme and adjust some colors in relation to my custom theme of the OS. Therefore it would be nice to be able using hex values to describe a color. So far I read and also look at the issues, there are only xterm color values supported. Is there a way to import a _Phython_ package to make this possible? Don't know how these theme classes are parsed, so...

**Comment by zjeffer** [comment]
So does this work now? I'd love to be able to use hex codes in themes.

**Comment by weilbith** [comment]
Sry, I'm using [powerlevel10k](https://github.com/romkatv/powerlevel10k). No clue if it works. :man_shrugging:
