### ISSUE TITLE
Directories not being shortened under Windows 10 GitBash

### ISSUE THREAD

**Issue by nick5435** [b-ryan/powerline-shell#339]
![untitled](https://user-images.githubusercontent.com/12479179/34214211-73597a28-e567-11e7-9d38-f04e8be95800.png)

Here's my config:
```json
{
    "segments": [
        "time",
        "git",
        "set_term_title",
        "cwd",
        "newline",
        "virtual_env",
        "exit_code",
        "username",
        "root"
    ],
    "hostname": {"colorize":"true"},
    "cwd": {
        "mode": "plain",
        "max_depth": 4,
        "full_cwd": "true",
        "max_dir_size": -1
    },
    "theme": "solarized_light",
    "mode":"patched" 
}
```

Python version is 3.6.4, just pulled powerline-shell from PyPI.

**Comment by b-ryan** [comment]
The `cwd` directory options are currently ignored when `plain` mode is used. I plan to fix that, but currently that's "expected" behavior.

**Comment by nick5435** [comment]
The directories still aren't being shortened after I remove the `"mode":"plain"` line from the config.

**Comment by b-ryan** [comment]
Could you post a screenshot of what it looks like without that option?

**Comment by nick5435** [comment]
![image](https://user-images.githubusercontent.com/12479179/34216260-5c51c348-e56d-11e7-9ae7-b9da9b6bdafd.png)

No change.

**Comment by nick5435** [comment]
Without any `cwd` config: it looks the same as well.

**Comment by b-ryan** [comment]
I think the code might thing your directory separator is `\` instead of `/`. What's the output of `python -c 'import os; print(os.sep)'`

**Comment by nick5435** [comment]
The result is `\`.

**Comment by b-ryan** [comment]
Is `python -c 'import os; print(os.path.sep)'` any different?

**Comment by b-ryan** [comment]
I don't think it will be. It looks like `os.sep` is just a copy of `os.path.sep`.

What is the output of `echo "$shell"`

**Comment by nick5435** [comment]
`/usr/bin/bash` which is just `C:\Program Files\Git\usr\bin\bash.exe`, but aliased. `$OS` is `Windows_NT`.

**Comment by b-ryan** [comment]
I think I have a solution. What's the output of `python -c 'import os; print(os.getcwd())'` ?

**Comment by nick5435** [comment]
`C:\Users\at8183jk\Desktop\Drive\Dropsync\School\Winona\ResearchProject\code`

**Comment by b-ryan** [comment]
Excellent. I will have a change that I believe will fix your issue. Just gimme a little bit.

**Comment by nick5435** [comment]
I'll work with a local version for a bit to see if this changes things.

**Comment by b-ryan** [comment]
By local version, you mean the PR I just opened? If so that would be great to confirm it resolves the issue.

**Comment by nick5435** [comment]
Yeah, I just pulled it down and locally installed it. I had to remove `'max_dir_size':-1` to get it to work (otherwise neither the ... nor the full name of any directories appeared, which is weird!). Otherwise it seems to be working!

**Comment by nick5435** [comment]
Another Weird thing: The git branch segment doesn't have the "arrow" appearance like the other ones do. Is that intentional?

**Comment by nick5435** [comment]
I did a little more digging, it seems if the `set_term_title` segment is empty, the segment before it will not have its arrow portion shown.

**Comment by b-ryan** [comment]
Ah interesting. Let's discuss in a separate issue.

**Comment by nick5435** [comment]
Issue with arrows moved to Issue #341
