### ISSUE TITLE
arrow disappeared from the address bar

### ISSUE THREAD

**Issue by sbmaruf** [b-ryan/powerline-shell#342]
I recently install powerline-shell both from github and pip. but it doesn't solve the problem. below is an example of my shell. there is no arrow in the shell address,
[![image.png](https://s10.postimg.org/4tkwq5ieh/image.png)](https://postimg.org/image/g5xi7xr39/)

**Comment by b-ryan** [comment]
Hi there, did you follow the instructions to install a patched font as described in https://github.com/b-ryan/powerline-shell#setup ?

**Comment by sbmaruf** [comment]
I followed the instruction. I solve the issue installing the fonts.
