### ISSUE TITLE
Ascii codec printing ordinal not in range(128)

### ISSUE THREAD

**Issue by omarchehab98** [b-ryan/powerline-shell#343]
This issue was directly addressed by #211, however, I have not been able to find a fix for this.

When changing directories into a directory with `git`, the pencil character is drawn

```
Traceback (most recent call last):
  File "/home/omar/.local/bin/powerline-shell", line 11, in <module>
    sys.exit(main())
  File "/home/omar/.local/lib/python3.5/site-packages/powerline_shell/__init__.py", line 206, in main
    sys.stdout.write(powerline.draw())
UnicodeEncodeError: 'ascii' codec can't encode character '\u270e' in position 546: ordinal not in range(128)
```

```
$  python3 --version
Python 3.5.3

$  pip show powerline-shell
Name: powerline-shell
Version: 0.4.5
Summary: A pretty prompt for your shell
Home-page: https://github.com/banga/powerline-shell
Author: Buck Ryan
Author-email: UNKNOWN
License: UNKNOWN
Location: /home/omar/.local/lib/python3.5/site-packages
Requires: argparse

$  uname -a
Linux omar 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux
```

As a temporary fix, I removed `git` from `segments` in `.powerline-shell.json`.

**Comment by b-ryan** [comment]
Sorry for the delay! This sounds similar to #229 - I am curious if the suggestion in there fixes this, specifically, setting:

export PYTHONIOENCODING=UTF-8

In your bashrc before the call to `powerline-shell`.

**Comment by b-ryan** [comment]
Since it's been over a month since my previous comment, going to close this. Feel free to re-open if needed!

**Comment by eightnoteight** [comment]
for anyone in future who gets here like myself, exporting `PYTHONIOENCODING` fixed the issue for me

**Comment by rklasen** [comment]
@eightnoteight thanks, this fixed the issue for me as well. specificallt, `export PYTHONIOENCODING='utf8'`. This was neccessary after issue #408 started appearing today.
