### ISSUE TITLE
"Import by filename is not supported" trying to use a custom theme

### ISSUE THREAD

**Issue by dainbrump** [b-ryan/powerline-shell#350]
I installed using the pip option and created the powerline-shell.json. I've cloned the repo just so I had the format of the theme classes correct. I copied the washed theme to a new theme file I called "skippy.py" in the themes dir. When I set skippy as the theme I want to use, and reload my terminal, I get:

Traceback (most recent call last):
  File "/usr/local/bin/powerline-shell", line 9, in <module>
    load_entry_point('powerline-shell==0.4.7', 'console_scripts', 'powerline-shell')()
  File "build/bdist.linux-x86_64/egg/powerline_shell/__init__.py", line 194, in main
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: Import by filename is not supported.

I've tried using the full path for the theme in the json, but still get the same error. I'm not a py guy, so I don't want to go poking in code I don't understand.

**Comment by b-ryan** [comment]
Fixed in #352 

You can use a full path for the theme now. Let me know if anything doesn't work!
