### ISSUE TITLE
error when entering a directory with io/__init__.py

### ISSUE THREAD

**Issue by nschloe** [b-ryan/powerline-shell#359]
When `cd`ing into a directory that has a subdirectory `io` with an `__init__.py` file in it – such as appearing in various Python projects –, powerline-shell shows the error message
```
Fatal Python error: Py_Initialize: can't initialize sys standard streams
```
I'm guessing it tries to pick up that very `io`. Import paths should probably be fixed.

**Comment by b-ryan** [comment]
hey @nschloe - I haven't been able to reproduce, which I think means this issue might be caused by how you have your PYTHONPATH set up. Do you modify your PYTHONPATH to include `.` by chance?

**Comment by nschloe** [comment]
I tried it now in a clean docker environment and wasn't able to reproduce either. I'll try and find out where the error comes from; if powerline-shell, I'll reopen the bug. Thanks for the feedback!
