### ISSUE TITLE
How to build manually for development?

### ISSUE THREAD

**Issue by Pl4gue** [b-ryan/powerline-shell#368]
Hey!
I would like to contribute to powerline-shell, but I am not sure how to set my development environment up correctly. Can you give me some tips? Or do I have to install `setup.py` everytime I change something in the segments?

**Comment by b-ryan** [comment]
Yeah good question. I should have put this in the readme by now. 

The first step is usually to set up a virtual environment. While not strictly necessary this is just a general thing to do for developing python projects. 

But to the heart of your question, no you don't need to run setup.py each time. Instead, run 

    ./setup.py develop

This will get things so you can make changes and have them take effect immediately.

**Comment by Pl4gue** [comment]
Thanks!
