### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by shawank** [b-ryan/powerline-shell#377]
![image](https://user-images.githubusercontent.com/22830708/37224784-7a64aa0a-23fa-11e8-9188-a96fc565a90f.png)

Hey, Could you help me figure out which all files are not on my system. I am using mac os with terminal. Does it has to do something with ANSI encoding. Why is it not rendering properly?
Thanks

**Comment by b-ryan** [comment]
I think there are two separate issues. I am not sure what the first is. Did you just install virtualenv?

As for the rendering, this is usually caused when you haven't installed a patched font. See the fonts here: https://github.com/powerline/fonts

**Comment by b-ryan** [comment]
Going to close since it's been over a month since my comment. Feel free to re-open if needed!
