### ISSUE TITLE
macOS issues with 0.5.2+

### ISSUE THREAD

**Issue by bre7** [b-ryan/powerline-shell#389]
After today's update, iTerm started displaying invalid chars (I tried resetting the fonts, uninstalling them, etc)

Even after disabling all segments, those chars (after the %) are displayed.

<img width="368" alt="screen shot 2018-04-22 at 02 55 05" src="https://user-images.githubusercontent.com/3183848/39092006-b2b3bba8-45d8-11e8-8324-edd83e917611.png">

> OS: macOS High Sierra
> iTerm Build 3.1.6beta5
> Powerline 0.5.3

Workaround:
```bash
 pip3 install 'powerline-shell==0.4.9' --force-reinstall
```

**Comment by b-ryan** [comment]
Damn thanks for reporting this. I know what this was. Will fix today

**Comment by b-ryan** [comment]
Change that caused this was reverted and deployed in 0.5.4 - let me know if you have any further issues.

**Comment by bytebeast** [comment]
@bre7 

I tested this on Mac also and did not see an issue. Going to try to reproduce and figure out why it worked on my mac but not on yours. Would really like to resolv the #248 bug. Can you provide me with the following:

1. Contents of .powerline-shell.json
```sh
cat ~/.powerline-shell.json
```

2. What shell are you using? and Version?

3. What is your TERM set to?
```sh
env | grep TERM
```

If its' possible for you to re-add the fix in  #249 and get the following info.

1. What is the content PS1?
```sh
env | grep PS1
```

2. What is the content of PROMPT_COMMAND?
```sh
env | grep PROMPT_COMMAND
```

Thanks!

**Comment by bre7** [comment]
Which version are you using ? The bug (solved in 0.5.4) was in versions 0.5.2 and 0.5.3

**Comment by bytebeast** [comment]
Ah good catch, I have not tried 0.5.3. I have been using a local fork of **master** with the #249 patch applied. Will try 0.5.3 shortly. Can you get the data for 0.5.3 for me... so I can use to debug.

Thanks

**Comment by bre7** [comment]
1. No content (file doesn't exist)
2. iTerm Build 3.1.6beta5
3- TERM=xterm-256color

---

Installed 0.5.3:

1. None
2. None
