### ISSUE TITLE
Why do I see question mark boxes [?]

### ISSUE THREAD

**Issue by thierrybo** [b-ryan/powerline-shell#398]
Hi,

I copy/paste the title from the faq because I tried several terminals, powerline fonts but still this ?

So my question is, with this config.json:
```
{
  "segments": [
    "virtual_env",
    "username",
    "ssh",
    "cwd", 
    "git",
    "git_stash",
    "jobs",
    "set_term_title",
    "newline",
    "root"
  ],
  "mode": "patched",
  "cwd": {
    "mode": "",
    "max_depth": 4
  },
  "vcs": {
    "show_symbol": true
  },
  "theme": "~/.config/powerline-shell/theme-thierrybo.py"
}
```
what GIT information is supposed to be displayed for the question mark in this screenshot?
![selection_001](https://user-images.githubusercontent.com/3847603/39481130-b25a7040-4d6a-11e8-8a94-fdae2b51fc9b.png)

**Comment by b-ryan** [comment]
Hey there @thierrybo - that question mark is part of the git segment - it indicates you have one untracked file in your repository.
