### ISSUE TITLE
Add support for perforce?

### ISSUE THREAD

**Issue by shikhanshu** [b-ryan/powerline-shell#401]
pretty please?

**Comment by b-ryan** [comment]
Oh jeez - that's a tall ask. I worked with perforce once almost ten years ago. I can't realistically support it myself.

What I would be happy to do is point to a third-party repository (yours perhaps?) where people can find the segment. A third-party segment listing has been on my mind for some time.

**Comment by shikhanshu** [comment]
Sounds good. If I come up with my own segment, will point you to it!

**Comment by b-ryan** [comment]
Yes I would be happy to
