### ISSUE TITLE
Contradictory Statements in Readme

### ISSUE THREAD

**Issue by d3signr** [b-ryan/powerline-shell#409]
Hi, 
I've just installed powerline-shell and have been working through the readme but have been left a bit confused at the config section. 

> Config File
> Powerline-shell is customizable through the use of a config file. This file is expected to be located at ~/.config/powerline-shell/config.json. You can generate the default config at this location using:
>
> powerline-shell --generate-config > ~/.powerline-shell.json
> (As an example, my config file is located here: here)

You state the config file is expected to be in **~/.config/powerline-shell/config.json** but then give the command to generate it under **~/** with a completely different name. So, which is it? The first stated location and filename, or the second?

Also you provide a link to your own config as an example. The link provided ends on a 404 not found.

Thanks for your time and hope you can provide some clarity.

**Comment by dbecker801** [comment]
I found the sample config at https://github.com/b-ryan/dotfiles/blob/master/home/config/powerline-shell/config.json, FWIW.

**Comment by b-ryan** [comment]
Whoops. My bad @d3signr - thanks for letting me know. The proper place is `~/.config/powerline-shell/config.json`. I will update the readme.
