### ISSUE TITLE
Cannot load theme.

### ISSUE THREAD

**Issue by Eel52** [b-ryan/powerline-shell#413]
Loading a theme by pointing powerline to it in the `config.json` file does not work. Even loading the default theme file `default.py` fails to work leading powerline-shell to throw the following error:

`Traceback (most recent call last):`
 ` File "/usr/bin/powerline-shell", line 11, in <module>`
`    sys.exit(main())`
 ` File "/usr/lib/python3.6/site-packages/powerline_shell/__init__.py", line 214, in main`
`    theme = read_theme(config)`
 ` File "/usr/lib/python3.6/site-packages/powerline_shell/__init__.py", line 177, in read_theme`
`    mod = importlib.import_module("powerline_shell.themes." + theme_name)`
`TypeError: must be str, not list`

Inserting any data where the path for the theme file is supposed to go within the `config.json` file, throws the same error. I have installed and reinstalled powerline-shell multiple times as well as test for the issue on different machines only to recieve the same error. 

My config.json follows:

`{`
 ` "segments": [`
`    "hostname",`
 `   "username",`
`    "ssh",`
 `   "cwd",`
`    "read_only",`
 `   "root"`
`  ]`
 `,"theme" : [`
`    "~/.config/powerline-shell/default.py"`
 ` ]`
`}`

**Comment by b-ryan** [comment]
Hey @Eel52 - the theme should not be a list, it should just be a string. Your config should be:

```
{
"segments": [
"hostname",
"username",
"ssh",
"cwd",
"read_only",
"root"
]
,"theme" : "~/.config/powerline-shell/default.py"
}
```

Make sure the path points to a real theme. The default configuration will not be at `~/.config/powerline-shell/default.py`.
