### ISSUE TITLE
How can I get rid of my name and hostname in a prompt

### ISSUE THREAD

**Issue by kenenbek** [b-ryan/powerline-shell#423]
I asked a question here:
https://askubuntu.com/questions/1063344/get-rid-of-name-and-hostname-in-a-terminal-prompt

**Comment by b-ryan** [comment]
Hey there -- this section of the docs explains how to customize your prompt: https://github.com/b-ryan/powerline-shell#customization

Basically your steps will be:

1. Create a config file using those instructions
2. Remove the username and hostname segments from the configuration

**Comment by kenenbek** [comment]
Yes, thank you very much!
