### ISSUE TITLE
[REQUEST] VI editing mode indicator

### ISSUE THREAD

**Issue by enricribas** [b-ryan/powerline-shell#429]
Love this, super simple and the first thing I install on new computer. Thank you!

It would be great to have VI mode indicator when using `set -o vi`.
I believe regular powerline installation has this but that is too hard to install. :)

**Comment by OliverLew** [comment]
There are some links to how to do this in bash and zsh:

[zsh vi mode status line](https://stackoverflow.com/a/3791786)
[The way to distinguish command-mode and insert-mode in Bash's Vi command line editing](https://stackoverflow.com/a/32614367)

For me, I am satisfied with this method in bash, I put the following in .inputrc:
```sh
# use vi mode
set editing-mode vi

# kill the lag, do not wait after ESC
set keyseq-timeout 0

# use block cursor to indicate command mode and pipe cursor insert mode
set show-mode-in-prompt on
set vi-cmd-mode-string "\1\e[2 q\2"
set vi-ins-mode-string "\1\e[6 q\2"
```

**Comment by enricribas** [comment]
Great! Thanks!
