### ISSUE TITLE
Powerline doesn't start after MacOS Mojave update

### ISSUE THREAD

**Issue by tshaterov** [b-ryan/powerline-shell#432]
Hi, 

I've updated my MacOS to the latest version - Mojave, and when I start the terminal (the default MacOS terminal), I have the following error 
`Extra data: line 71 column 1 (char 5292)`

Here is my .bash_profile file content : 

`export PATH=$PATH:$HOME/Library/Python/2.7/bin
powerline-daemon -q
POWERLINE_BASH_CONTINUATION=1
POWERLINE_BASH_SELECT=1
. /Users/tshaterov/Library/Python/2.7/lib/python/site-packages/powerline/bindings/bash/powerline.sh`

Any ideas what can be going wrong with it?

**Comment by b-ryan** [comment]
hey @tshaterov - I think you have the wrong project: https://github.com/powerline/powerline
