### ISSUE TITLE
Do you know what this blue "1" means?

### ISSUE THREAD

**Issue by rawadrifai** [b-ryan/powerline-shell#464]
It shows up in every repo and it just started happening.

![image](https://user-images.githubusercontent.com/24530625/59981832-38c0e000-95be-11e9-992e-17398ba2dc7a.png)

**Comment by rawadrifai** [comment]
it disappeared after I closed the terminal. lol.

**Comment by jceaser** [comment]
If your running the default configurations I think it might be the number of jobs that are running in that shell
