### ISSUE TITLE
Make the Shell Prompt a lamda

### ISSUE THREAD

**Issue by sreyan32** [b-ryan/powerline-shell#490]
Is there any way to denote the shell prompt in powerline via a different symbol ? I want to denote it via the lambda on a new line. Like for example:

```
sreyan32@localhost > ~/Desktop >
λ 
```
I still want the powerline display but just a different character for a lambda.

**Comment by lucknaumann** [comment]
If you're still looking for an answer to this, you need to edit the root.py file located wherever powerline_shell installed on your system. Typing `pip show powerline-shell` will show where it's installed under 'Location'. Open ..\powerline_shell\segments\root.py in a text editor and edit the appropriate shell symbol.

[reference](https://github.com/b-ryan/powerline-shell/blob/master/powerline_shell/segments/root.py)

**Comment by jdgregson** [comment]
I'm also interested in doing something like this, but mine seems to be installed as an `.egg` file. Is there any way to add a newline after the prompt in this case?

    > pip show powerline-shell
    Name: powerline-shell
    Version: 0.7.0
    Summary: A pretty prompt for your shell
    Home-page: https://github.com/b-ryan/powerline-shell
    Author: Buck Ryan
    Author-email: buck@buckryan.com
    License: MIT
    Location: /Users/<username>/Library/Python/3.9/lib/python/site-packages/powerline_shell-0.7.0-py3.9.egg
    Requires: argparse
    Required-by:
