### ISSUE TITLE
Getting "Big Bang" Near My Hostname

### ISSUE THREAD

**Issue by spectrumgamer75** [b-ryan/powerline-shell#511]
Hello,
I have installed it successfully, but when I open the terminal I get this "big bang" text near my host name:
![hwghee](https://user-images.githubusercontent.com/72115696/103434611-f7d16f00-4c29-11eb-9745-f5011b8544a0.png)

Any way to remove this?

**Comment by spectrumgamer75** [comment]
Also, I am using this in xfce DE with xfce terminal. The same happens when I tried lxde terminal

**Comment by PC1266** [comment]
here too
![image](https://user-images.githubusercontent.com/47820634/147456635-c4f8aa3f-4e85-4603-a304-2ecdf7b1bb8d.png)

**Comment by FilippoUslenghi** [comment]
@spectrumgamer75 
How did you resolve it? I'm having the same issue

**Comment by versayr** [comment]
@FilippoUslenghi I assume you've fixed this, but for any others who find this thread like I did - the text 'Big Bang' will show in powerline when the working directory is a new git project, before the first commit. Do a commit and the text will switch to the name of the working branch.
