### ISSUE TITLE
Separators are darker than backgrounds in iTerm2 with transparency

### ISSUE THREAD

**Issue by sentience** [b-ryan/powerline-shell#53]
Having switched to iTerm2 on the advice given in #52, I now have the opposite problem: separators are darker than the backgrounds they are supposed to match:

![Screen_Shot_2013-01-16_at_1 18 16_PM](https://f.cloud.github.com/assets/89772/70143/552b6fc6-5f83-11e2-8caa-38f77bc45cdd.png)

This issue seems to disappear when transparency is disabled in iTerm2.

**Comment by polarathene** [comment]
Came across this issue when troubleshooting via Google, in case anyone else lands here I've made a [PR for iTerm2](https://github.com/gnachman/iTerm2/pull/277) that should hopefully get merged to fix this issue :)
