### ISSUE TITLE
segment/jobs does not work in bash on Ubuntu 20.04

### ISSUE THREAD

**Issue by cbeach** [b-ryan/powerline-shell#530]
> pip freeze | grep powerline
> powerline-shell==0.7.0

The number of jobs always evaluates to -1.
The same version of powerline-shell works in Ubuntu 18.04

**Comment by b-ryan** [comment]
I'm trying to understand how things ever worked. I traced the current behavior back to https://github.com/b-ryan/powerline-shell/pull/99 but I have the same issue as you do, this doesn't work and I'm using Ubuntu 22.

I wonder if bash changed the behavior of `$()` in more recent versions. Do you use bash?

**Comment by b-ryan** [comment]
https://github.com/b-ryan/powerline-shell/issues/228 related

**Comment by b-ryan** [comment]
Looks like this may be the answer: https://stackoverflow.com/questions/20725925/get-pid-of-current-subshell -- bash did change the behavior at one point

**Comment by b-ryan** [comment]
Just pushed a commit that should fix this. I will get a release out soon.
