### ISSUE TITLE
I have some question for you

### ISSUE THREAD

**Issue by Ryangithub10** [b-ryan/powerline-shell#532]
Hi b-ryan, i have some question for you

1. How i configure my powerline prompt
2. How i adding icons to my prompt
3. How i adding new prompt in right side

I hope i get a answer for you.

Btw your prompt is nice, i was use your prompt as long as 2 day until this day. 👍

Oh yeah, i have one question anymore:

i was download and install powerline prompt manually, so do i have to install a dependencies like powerline git status and such?

**Comment by b-ryan** [comment]
Hi @Ryangithub10 

Sorry for the delay! To be honest, I haven't been keeping up with this repo, but I am intending to change that!

1. There are notes in the README about configuration, here: https://github.com/b-ryan/powerline-shell#customization -- if you let me know what you are trying to customize, I can help you more specifically
2. Currently there isn't a way to add icons, unfortunately. I am working on a way to fix that
3. Unfortunately, there is no right side prompt support yet either
4. There are no dependencies other than Python
