### ISSUE TITLE
Paginação da Área de Search

### ISSUE THREAD

**Issue by caciano4** [b-ryan/powerline-shell#533]
Paginação da Área de Search
Observação:
Foi uma área que iniciaram porem por falta de definição não pode ser finalizado ou algo assim.

![WhatsApp Image 2022-03-25 at 09 39 11](https://user-images.githubusercontent.com/74930710/160124668-2fa3735e-0189-40de-8dba-2fb4119734b6.jpeg)

**Comment by b-ryan** [comment]
Sorry I think you must have the wrong project.
